### ISSUE TITLE
Banner title font should be ASAP Medium as per psd design.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Plastic-Fabricators#11]
![image](https://cloud.githubusercontent.com/assets/12791909/11259755/5ffae870-8e9f-11e5-81d4-8192b99057b2.png)

**Comment by asif-titan** [comment]
The Google API from where we are getting the fonts doesn't have font-weight medium it just has normal and bold.

**Comment by ermatitan** [comment]
You can change the font weight to 500 since it's just the same with the font "Medium".
