### ISSUE TITLE
Why is it that a list of product repeater is included in the product category post? 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Plastic-Fabricators#22]
![image](https://cloud.githubusercontent.com/assets/12791909/11263082/1ab3a4c8-8ec2-11e5-9d98-40b3bb62932d.png)

**Comment by asif-titan** [comment]
as per the design brief, they do not want to show any products just product categories with a listing of the products that belong to that category, that is the reason i have used the repeater field.

**Comment by ermatitan** [comment]
Why is it that the product repeater not mentioned in the project scope?

**Comment by asif-titan** [comment]
The scope has been updated to reflect the DB
