### ISSUE TITLE
Product Single page not properly designed.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Plastic-Fabricators#25]
![image](https://cloud.githubusercontent.com/assets/12791909/11263789/007513ce-8ec9-11e5-9948-c9975fd8a75b.png)

**Comment by asif-titan** [comment]
As per the the design brief there are no products to be shown that is why the product listing and product single pages been designed.

**Comment by ermatitan** [comment]
Please confirm this to your Manager since project scope indicates a single product page. Thanks

![image](https://cloud.githubusercontent.com/assets/12791909/11553901/16bffc1a-99ce-11e5-9552-701a00fd5383.png)

**Comment by asif-titan** [comment]
I have Confirmed it with the TL scope has been updated to reflect DB

**Comment by ermatitan** [comment]
Product scope is updated so I am marking this as fix

**Comment by saif-titan** [comment]
You have commented that you are marking it as fixed but did not close this issue.
Thanks

**Comment by ermatitan** [comment]
All product post are disabled as per design and can no longer be access. So marking this as fix
