### ISSUE TITLE
Sidebar: Spacing for long product category title is too huge.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Plastic-Fabricators#26]
![image](https://cloud.githubusercontent.com/assets/12791909/11263880/dd02ec8a-8ec9-11e5-8b2f-d5d74891e5d3.png)

**Comment by asif-titan** [comment]
As per the design the line-height of the category and service title is 50px, that gap is due to the line height.

**Comment by ermatitan** [comment]
The in-line height can only affect the spacing between each category listing but should not affect  the spacing in each element.
