### ISSUE TITLE
Checkout: Please align First and Last Name field in both Billing Details and Ship to Different Address.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Plastic-Fabricators#30]
![image](https://cloud.githubusercontent.com/assets/12791909/11264182/84c343be-8ecc-11e5-8d7f-3e2a46306f50.png)

**Comment by asif-titan** [comment]
These pages are not required for woocommerce showcase sites.

**Comment by ermatitan** [comment]
All pages related to wooCommerce should be working properly. If you choose not to fix the issue just disable add to cart button in order for this page not to show up. Thanks

**Comment by kabirkhan123** [comment]
Cart button is disabled.

**Comment by ermatitan** [comment]
All product post are disabled as per design. The cart button also no longer displayed, so Im marking this as fix
