### ISSUE TITLE
Product: Product title not aligned.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Plastic-Fabricators#32]
![image](https://cloud.githubusercontent.com/assets/12791909/11264400/23a1ac68-8ece-11e5-9c2d-0a331878e085.png)

**Comment by asif-titan** [comment]
As per the the design brief there are no products to be shown that is why the product listing and product single pages been designed.

**Comment by ermatitan** [comment]
As per my Manager, all pack 1 and 2 project should not use WooCommerce, you can use a custom post in displaying the product categories. But if you insist in using the WooCommerce, you need to disable or hide the product post created so that it will not show up on the category single page. Thanks

**Comment by ermatitan** [comment]
All product post are disabled as per design and no longer displayed on the front-end
