### ISSUE TITLE
Cart - Nothing happens when you click on the Apply Coupon button without adding any code on the coupon box.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Plastic-Fabricators#33]
![image](https://cloud.githubusercontent.com/assets/12791909/11264553/72044dba-8ecf-11e5-86fc-a13d841519d5.png)

**Comment by asif-titan** [comment]
These pages are not required for woocommerce showcase sites.

**Comment by ermatitan** [comment]
Please disable add to cart button in order for this page not to show up. Thanks

**Comment by kabirkhan123** [comment]
Cart button is disabled.

**Comment by ermatitan** [comment]
All product post are disabled as per design. The cart button also no longer displayed, so Im marking this as fix
