### ISSUE TITLE
Want to Work with us thumbnails displays on product and services listing pages as well as in every category listing page. Questions: Where should exactly this thumbnails be displayed? 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Plastic-Fabricators#54]
![image](https://cloud.githubusercontent.com/assets/12791909/11290297/9e9591ee-8f70-11e5-904c-00e9c8ef6562.png)

**Comment by asif-titan** [comment]
As per the design is displayed on the category and service listing pages.
