### ISSUE TITLE
Checkout: Woo commerce error list has unidentified list image

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Plastic-Fabricators#56]
![image](https://cloud.githubusercontent.com/assets/12791909/11290908/c83651b4-8f75-11e5-88c1-b601a8f80c6a.png)

**Comment by asif-titan** [comment]
These pages are not required for woocommerce showcase sites.

**Comment by ermatitan** [comment]
Please disable add to cart button in order for this page not to show up. Thanks

**Comment by kabirkhan123** [comment]
Cart button  is disabled.

**Comment by ermatitan** [comment]
All product post are disabled as per design. The cart button also no longer displayed, so Im marking this as fix
