### ISSUE TITLE
Mobile : Cart - Coupon input box and apply coupon button overlaps.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Plastic-Fabricators#57]
Ipad Air

![image](https://cloud.githubusercontent.com/assets/12791909/11290950/1d94109c-8f76-11e5-8be1-8a03791802dc.png)

**Comment by asif-titan** [comment]
These pages are not required for woocommerce showcase sites.

**Comment by ermatitan** [comment]
Please disable add to cart button in order for this page not to show up. Thanks

**Comment by kabirkhan123** [comment]
Cart page is removed.

**Comment by ermatitan** [comment]
All product post are disabled as per design. The cart button also no longer displayed, so Im marking this as fix
