### ISSUE TITLE
Homepage: Featured products should only the latest 4 products not the product category. Featured product currently displays the product category.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Plastic-Fabricators#69]
![image](https://cloud.githubusercontent.com/assets/12791909/11293345/4c2c1210-8f94-11e5-8ba9-76386ea4bbaf.png)

**Comment by asif-titan** [comment]
As per design brief products are not being shown only categories are going to be shown on the site, that is the reason categories are shown under featured products.

**Comment by ermatitan** [comment]
As per my Manager, all pack 1 and 2 project should not use WooCommerce, you can use a custom post in displaying the product categories. But if you insist in using the WooCommerce, you need to disable or hide the product post created so that it will not show up on the category single page. Thanks

**Comment by saif-titan** [comment]
Removed the product post.

**Comment by ermatitan** [comment]
All product post are disabled as per design, so Im marking this as fix
