### ISSUE TITLE
General: Inconsistency for H2 heading font size. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Plastic-Fabricators#74]
About Us page - H2 heading measures 36px

News and FAQ list title which is also uses the H2 heading only measures 24px.

**Comment by asif-titan** [comment]
As per the design the General H2 Font-size is 36px which is given in the About Us page,
As per HTML standards the heading tags are used to show the importance of the content it is representing, H1 is used for the most important heading that is the page title, then H2 is used to the next important section of the page, that is the reason H2 is being used for the post titles, font-size  used as per the design given for the News and FAQ listing page.
